baseURL = "https://piquette.io/"
languageCode = "en-us"
title = "Piquette"
googleAnalytics = ""

### -------------------------------
# Site-wide params.
### -------------------------------
[params]
    enableRobotsTXT = true
    pluralizeListTitles = false
    pluralizelisttitles = false
    description = "Open source project portal"
    githubUsername = "piquette"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "R"]

### -------------------------------
# Main menu.
### -------------------------------
[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 1
    identifier = "folder-open"

[[menu.main]]
    url = "/research/"
    name = "Research"
    weight = 2
    identifier = "flask"

[[menu.main]]
    url = "/snippets/"
    name = "Snippets"
    weight = 3
    identifier = "code-branch"

[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 4
    identifier = "tags"
